# base images
FROM ubuntu:latest

# run command
RUN echo Hello Its shell type command
RUN ["echo", "Hello its exec type command"]
RUN ["/bin/bash", "-c", "echo `Hello its /bin/bash execution in shell type command`"]
